//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.TicariOtomasyon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBANKA
    {
        public int ID { get; set; }
        public string BANKAADI { get; set; }
        public string SUBE { get; set; }
        public string IBAN { get; set; }
        public string HESAPNO { get; set; }
        public string YETKILI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string HESAPTURU { get; set; }
    }
}
