//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.TicariOtomasyon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGIDERLER
    {
        public int ID { get; set; }
        public Nullable<decimal> ELEKTIRIK { get; set; }
        public Nullable<decimal> SU { get; set; }
        public Nullable<decimal> DOGALGAZ { get; set; }
        public Nullable<decimal> INTERNET { get; set; }
        public Nullable<decimal> MAASLAR { get; set; }
        public Nullable<decimal> EKSTRA { get; set; }
        public string EKSTRADETAY { get; set; }
        public string TARIH { get; set; }
    }
}
